apiVersion: v2
appVersion: "0.1.1"
description: âš¡ï¸ Gitlab notifier for Slack ğŸ”‹
icon: https://avatars.githubusercontent.com/u/46966179?s=200&v=4
name: turbo-enigma
type: application
version: 0.1.1
